import type {
  Category,
  Item,
  ItemAddOn,
  ItemModifier,
  ItemVariant,
  Modifier,
} from "../types";

export const categoryFallback = "#e5e7eb";

export const categoryColors = [
  "#f8cfc1",
  "#d8e7ca",
  "#c9e5f6",
  "#f5ddaa",
  "#d9d4f4",
  "#f6c8d8",
];

const seededAt = new Date().toISOString();

export const seedCategories: Category[] = [
  {
    id: "cat_coffee",
    name: "Coffee",
    defaultColor: "#f8cfc1",
    createdAt: seededAt,
  },
  {
    id: "cat_tea",
    name: "Tea",
    defaultColor: "#d8e7ca",
    createdAt: seededAt,
  },
  {
    id: "cat_sandwiches",
    name: "Sandwiches",
    defaultColor: "#f5ddaa",
    createdAt: seededAt,
  },
  {
    id: "cat_rice_meals",
    name: "Rice Meals",
    defaultColor: "#d9d4f4",
    createdAt: seededAt,
  },
  {
    id: "cat_sodas",
    name: "Sodas",
    defaultColor: "#c9e5f6",
    createdAt: seededAt,
  },
];

export const seedItems: Item[] = [
  {
    id: "item_americano",
    name: "Americano",
    price: 11000,
    categoryId: "cat_coffee",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_latte",
    name: "Latte",
    price: 11000,
    categoryId: "cat_coffee",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_cappuccino",
    name: "Cappuccino",
    price: 11000,
    categoryId: "cat_coffee",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_mocha",
    name: "Mocha",
    price: 11000,
    categoryId: "cat_coffee",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_caramel_macchiato",
    name: "Caramel Macchiato",
    price: 11000,
    categoryId: "cat_coffee",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_black_tea",
    name: "Black Tea",
    price: 10000,
    categoryId: "cat_tea",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_green_tea",
    name: "Green Tea",
    price: 10000,
    categoryId: "cat_tea",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_jasmine_tea",
    name: "Jasmine Tea",
    price: 10000,
    categoryId: "cat_tea",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_milk_tea",
    name: "Milk Tea",
    price: 10000,
    categoryId: "cat_tea",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_lemon_tea",
    name: "Lemon Tea",
    price: 10000,
    categoryId: "cat_tea",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_ham_cheese_sandwich",
    name: "Ham & Cheese Sandwich",
    price: 7000,
    categoryId: "cat_sandwiches",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_tuna_melt_sandwich",
    name: "Tuna Melt Sandwich",
    price: 7500,
    categoryId: "cat_sandwiches",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_chicken_club_sandwich",
    name: "Chicken Club Sandwich",
    price: 8000,
    categoryId: "cat_sandwiches",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_egg_salad_sandwich",
    name: "Egg Salad Sandwich",
    price: 8500,
    categoryId: "cat_sandwiches",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_roast_beef_sandwich",
    name: "Roast Beef Sandwich",
    price: 9000,
    categoryId: "cat_sandwiches",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_chicken_teriyaki_rice",
    name: "Chicken Teriyaki Rice",
    price: 12000,
    categoryId: "cat_rice_meals",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_beef_tapa_rice",
    name: "Beef Tapa Rice",
    price: 13000,
    categoryId: "cat_rice_meals",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_pork_tonkatsu_rice",
    name: "Pork Tonkatsu Rice",
    price: 14000,
    categoryId: "cat_rice_meals",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_spicy_pork_rice",
    name: "Spicy Pork Rice",
    price: 15000,
    categoryId: "cat_rice_meals",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_salmon_rice_bowl",
    name: "Salmon Rice Bowl",
    price: 16000,
    categoryId: "cat_rice_meals",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_coke",
    name: "Coke",
    price: 2500,
    categoryId: "cat_sodas",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_sprite",
    name: "Sprite",
    price: 2500,
    categoryId: "cat_sodas",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_royal",
    name: "Royal",
    price: 2500,
    categoryId: "cat_sodas",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_mountain_dew",
    name: "Mountain Dew",
    price: 2500,
    categoryId: "cat_sodas",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "item_7_up",
    name: "7-Up",
    price: 2500,
    categoryId: "cat_sodas",
    isOutOfStock: false,
    isAddOn: false,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_shot",
    name: "Extra Shot",
    price: 2500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_oatmilk",
    name: "Oatmilk",
    price: 2500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_non_fat",
    name: "Non-Fat",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_cheese",
    name: "Extra Cheese",
    price: 1500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_ham",
    name: "Extra Ham",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_tomato_slice",
    name: "Tomato Slice",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_tuna_spread",
    name: "Tuna Spread",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_melted_cheese",
    name: "Melted Cheese",
    price: 1500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_pickle_slices",
    name: "Pickle Slices",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_bacon_strip",
    name: "Bacon Strip",
    price: 2500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_grilled_chicken",
    name: "Grilled Chicken",
    price: 3000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_garlic_mayo",
    name: "Garlic Mayo",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_boiled_egg",
    name: "Boiled Egg",
    price: 1500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_lettuce",
    name: "Lettuce",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_roast_beef_slice",
    name: "Roast Beef Slice",
    price: 3500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_caramelized_onions",
    name: "Caramelized Onions",
    price: 1500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_rice",
    name: "Extra Rice",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_kimchi_rice",
    name: "Extra Kimchi Rice",
    price: 3000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_extra_garlic_rice",
    name: "Extra Garlic Rice",
    price: 2500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_garlic_rice_upgrade",
    name: "Garlic Rice Upgrade",
    price: 500,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_kimchi_rice_upgrade",
    name: "Kimchi Rice Upgrade",
    price: 1000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_coke",
    name: "Coke",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_sprite",
    name: "Sprite",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_royal",
    name: "Royal",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_mountain_dew",
    name: "Mountain Dew",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
  {
    id: "addon_7_up",
    name: "7-Up",
    price: 2000,
    categoryId: null,
    isOutOfStock: false,
    isAddOn: true,
    createdAt: seededAt,
  },
];

const coffeeDrinkIds = [
  "item_americano",
  "item_latte",
  "item_cappuccino",
  "item_mocha",
  "item_caramel_macchiato",
];

const sweetenedCoffeeDrinkIds = coffeeDrinkIds.filter((itemId) => itemId !== "item_americano");

const teaDrinkIds = [
  "item_black_tea",
  "item_green_tea",
  "item_jasmine_tea",
  "item_milk_tea",
  "item_lemon_tea",
];

const riceMealIds = [
  "item_chicken_teriyaki_rice",
  "item_beef_tapa_rice",
  "item_pork_tonkatsu_rice",
  "item_spicy_pork_rice",
  "item_salmon_rice_bowl",
];

function createSizeVariants(itemIds: string[], prices: { small: number; medium: number; large: number }) {
  return itemIds.flatMap((itemId) => [
    {
      id: `var_${itemId}_small`,
      itemId,
      name: "Small",
      price: prices.small,
      sortOrder: 1,
      createdAt: seededAt,
    },
    {
      id: `var_${itemId}_medium`,
      itemId,
      name: "Medium",
      price: prices.medium,
      sortOrder: 2,
      createdAt: seededAt,
    },
    {
      id: `var_${itemId}_large`,
      itemId,
      name: "Large",
      price: prices.large,
      sortOrder: 3,
      createdAt: seededAt,
    },
  ]);
}

export const seedItemVariants: ItemVariant[] = [
  ...createSizeVariants(coffeeDrinkIds, { small: 10000, medium: 11000, large: 12000 }),
  ...createSizeVariants(teaDrinkIds, { small: 9000, medium: 10000, large: 11000 }),
];

export const seedModifiers: Modifier[] = [
  {
    id: "mod_temperature",
    label: "Hot or Cold",
    options: ["Hot", "Cold"],
    createdAt: seededAt,
  },
  {
    id: "mod_sugar_level",
    label: "Sugar Level",
    options: ["100", "75", "50", "25", "0"],
    createdAt: seededAt,
  },
];

function linkModifier(modifierId: string, itemIds: string[]) {
  return itemIds.map((itemId) => ({
    id: `im_${itemId}_${modifierId}`,
    itemId,
    modifierId,
  }));
}

export const seedItemModifiers: ItemModifier[] = [
  ...linkModifier("mod_temperature", [...coffeeDrinkIds, ...teaDrinkIds]),
  ...linkModifier("mod_sugar_level", [...sweetenedCoffeeDrinkIds, ...teaDrinkIds]),
];

function linkAddOns(addOnItemIds: string[], itemIds: string[]) {
  return itemIds.flatMap((itemId) =>
    addOnItemIds.map((addOnItemId) => ({
      id: `iao_${itemId}_${addOnItemId}`,
      itemId,
      addOnItemId,
    })),
  );
}

export const seedItemAddOns: ItemAddOn[] = [
  ...linkAddOns(["addon_extra_shot", "addon_oatmilk", "addon_non_fat"], coffeeDrinkIds),
  ...linkAddOns(["addon_extra_cheese", "addon_extra_ham", "addon_tomato_slice"], [
    "item_ham_cheese_sandwich",
  ]),
  ...linkAddOns(["addon_tuna_spread", "addon_melted_cheese", "addon_pickle_slices"], [
    "item_tuna_melt_sandwich",
  ]),
  ...linkAddOns(["addon_bacon_strip", "addon_grilled_chicken", "addon_garlic_mayo"], [
    "item_chicken_club_sandwich",
  ]),
  ...linkAddOns(["addon_boiled_egg", "addon_lettuce", "addon_melted_cheese"], [
    "item_egg_salad_sandwich",
  ]),
  ...linkAddOns(["addon_roast_beef_slice", "addon_caramelized_onions", "addon_extra_cheese"], [
    "item_roast_beef_sandwich",
  ]),
  ...linkAddOns(
    [
      "addon_extra_rice",
      "addon_extra_kimchi_rice",
      "addon_extra_garlic_rice",
      "addon_garlic_rice_upgrade",
      "addon_kimchi_rice_upgrade",
      "addon_coke",
      "addon_sprite",
      "addon_royal",
      "addon_mountain_dew",
      "addon_7_up",
    ],
    riceMealIds,
  ),
];
